# Generated by Django 2.2.12 on 2020-10-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailauth',
            old_name='life_time',
            new_name='time_create',
        ),
    ]
