# Generated by Django 2.2.12 on 2020-10-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201006_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauth',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
