# Generated by Django 2.2.12 on 2020-11-01 08:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_passwordreset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailAuth',
            new_name='EmailAuthAsk',
        ),
    ]
