# Generated by Django 3.1 on 2021-01-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210119_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
    ]
