from .animal_news import AnimalNewsSerializer
from .search_advert import UrlAnimalAdvertSerializer
from .search_news import UrlAnimalNewsSerializer
from .serializers_animal import AnimalColorSerializer,AnimalTypeSerializer,AnimalInfoSerializer,CommentSerializer