var MediaMetricsRating=[
[30742803, "Вспышка неизвестной и пугающей болезни началась в Индии", "togliatti24.ru", "togliatti24.ru/post/view/4503/"],
[72776174, "Что известно о последних днях Армена Джигарханяна?", "www.aif.ru", "www.aif.ru/culture/person/chto_izvestno_o_poslednih_dnyah_armena_dzhigarhanyana"],
[50764941, "Суд отложен: Обвиняемый в смертельном ДТП в Твери находится на лечении", "tver.aif.ru", "tver.aif.ru/incidents/details/sud_otlozhen_obvinyaemyy_v_smertelnom_dtp_v_tveri_nahoditsya_na_lechenii"],
[40290984, "В Башкирии увеличили штрафы за торговлю в неустановленных местах", "www.kommersant.ru", "www.kommersant.ru/doc/4604613"],
[53490884, "Отчим избил малышей 2 и 4 лет и выбросил на мороз за съеденный кусочек колбасы", "tarakann.ru", "tarakann.ru/zhizn/otchim-izbil-malyshej-2-i-4-let-i-vybrosil-na-moroz-za-sedennyj-kusochek-kolbasy/"],
[51016720, "Потенциал агропродовольственного кластера в Башкирии оценили в 150 млрд", "ufa.rbc.ru", "ufa.rbc.ru/ufa/08/12/2020/5fcf72a59a7947665d33d779"],
[71418986, "Названы новые поводы лишиться водительских документов", "tvtver.ru", "tvtver.ru/news/nazvany-novye-povody-lishitsya-voditelskih-dokumentov/"],
[52911962, "В истории с суррогатными младенцами нашли следы чёрных трансплантологов", "pnp.ru", "pnp.ru/social/v-istorii-s-surrogatnymi-mladencami-nashli-sledy-chyornykh-transplantologov.html"],
[56152455, "Избран новый председатель профкома КАМАЗа [фото]", "chelny-izvest.ru", "chelny-izvest.ru/news/facts/izbran-novyy-predsedatel-profkoma-kamaza-foto"],
[41702664, "В Кирове насмерть сбили 20-летнюю девушку", "vyatka-grad.ru", "vyatka-grad.ru/archives/69362"],
[65969115, "Вступило в законную силу решение Мичуринского городского суда по делу о поджоге внедорожника", "www.michurinsk.ru", "www.michurinsk.ru/news/crime/33399.html"],
[57771945, "Рубен Оганесян возглавил направление цифровой трансформации холдинга «Медиа-1»", "adindex.ru", "adindex.ru/news/hr/2020/12/8/287430.phtml"],
[70695990, "Тестирование Cyberpunk 2077: RTX 3090 обеспечивает 4К при 60 кадрах/с только с DLSS", "3dnews.ru", "3dnews.ru/1027287/testirovanie-cyberpunk-2077-rtx-3090-obespechivaet-4k-pri-60-kadrahs-tolko-s-dlss"],
[15136058, "В Кирове на перекрестке погибла 20-летняя девушка-пешеход", "newsler.ru", "newsler.ru/incidents/2020/12/08/v-kirove-na-perekrestke-pogibla-20-letnyaya-devushka-peshehod"],
[52203094, "Ушел из жизни один из самых известных художников Кинешмы Евгений Чистов", "kineshemec.ru", "kineshemec.ru/news/obshhestvo-zhizn/ushel-iz-zhizni-odin-iz-samyh-izvestnyh-khudozhnikov-kineshmy-jevgenij-chistov-28702.html"],
[56386405, "Жизнь за целлофаном: история ковидной пациентки из «красной зоны» Бавлов", "sntat.ru", "sntat.ru/news/society/08-12-2020/zhizn-za-tsellofanom-istoriya-kovidnoy-patsientki-iz-krasnoy-zony-bavlov-5790910"],
[28561431, "На трассе в Татарстане лоб в лоб столкнулись «УАЗ» и микроавтобус, есть погибшие", "kukmor-rt.ru", "kukmor-rt.ru/news/poslednie-novosti/na-trasse-v-tatarstane-lob-v-lob-stolknulis-uaz-i-mikroavtobus-est-pogibshie"],
[34561457, "Жителям Тверской области придётся освободить подвалы и чердаки", "toptver.ru", "toptver.ru/lenta/zhiteljam-tverskoj-oblasti-pridjotsja-osvobodit-podvaly-i-cherdaki/"],
[34916745, "Антибиотик против ожирения", "www.nkj.ru", "www.nkj.ru/news/40015/"],
[57797914, "В Королеве вывесили на дом плакат с именами должников по ЖКХ", "m24.ru", "m24.ru/videos/obshchestvo/08122020/269005"],
[67789319, "Глава Роспотребнадзора перечислила регионы с самой сложной ситуацией по COVID-19", "lenta.ru", "lenta.ru/news/2020/12/08/region/"],
[38360241, "С 1 января 2021 года в Кировской области будут применять новые нормативы накопления ТКО", "vyatka-grad.ru", "vyatka-grad.ru/archives/69365"],
[70378291, "В центре Кирова внедорожник сбил насмерть 20-летнюю девушку", "www.new-variant.ru", "www.new-variant.ru/archives/185556"],
[43572839, "Гуаньча (Китай): китайский зонд впервые осуществил сближение и стыковку на лунной орбите и передачу образцов", "inosmi.ru", "inosmi.ru/social/20201208/248695766.html"],
[41182965, "«Спутник V» наделал шума: что говорят иностранцы о российской вакцине от коронавируса", "www.tverlife.ru", "www.tverlife.ru/lenta/sputnik-v-nadelal-shuma-chto-govorjat-inostrancy-o-rossijskoj-vakcine-ot-koronavirusa/"],
[58342652, "«Оба водителя насмерть». Пензенцы сообщают о страшном ДТП возле Елюзани — В сети — Пенза Взгляд", "penzavzglyad.ru", "penzavzglyad.ru/net/102615/penzency-soobschayut-o-strashnom-dtp-vozle-elyuzani"],
[39280166, "Какой в России будет зима 2020-2021 – прогноз руководителя Гидрометцентра России", "vedtver.ru", "vedtver.ru/news/society/kakoy-v-rossii-budet-zima-2020-2021-prognoz-rukovoditelya-gidromettsentra-rossii/"],
[62868318, "Женщину экстренно доставили на вертолёте в Тверь", "toptver.ru", "toptver.ru/lenta/zhenshhinu-jekstrenno-dostavili-na-vertoljote-v-tver/"],
[110575785, "200-рублевую купюру в Челнах продают за 2 миллиона рублей [фото]", "chelny-izvest.ru", "chelny-izvest.ru/news/facts/200-rublevuyu-kupyuru-v-chelnakh-prodayut-za-2-milliona-rubley-foto"],
[67526935, "В Тверской области загорелся дом с хлебным павильоном", "toptver.ru", "toptver.ru/lenta/v-tverskoj-oblasti-zagorelsja-dom-s-hlebnym-pavilonom/"],
[15336821, "Три препарата, которыми стоит запастись впрок на время пандемии коронавируса. И это не антибиотики", "runaruna.ru", "runaruna.ru/articles/34140-tri-preparata-kotorimi-stoit-zapastis-vprok-na-vremya-pandemii-koronavirusa-i-eto-ne-antibiotiki/"],
[68957669, "Введенные из-за COVID-19 требования для школ продлили до конца следующего года", "nversia.ru", "nversia.ru/news/vvedennye-iz-za-covid-19-trebovaniya-dlya-shkol-prodlili-do-konca-sleduyuschego-goda/"],
[36005663, "Губернатор Шумков сделал важное заявление по поводу зарплат", "oblast45.ru", "oblast45.ru/publication/36063"],
[29972408, "Директор детского лагеря загремел в уголовку с фиктивными поставками призов", "chelny-biz.ru", "chelny-biz.ru/news/360860/"],
[33950696, "Мичуринские таксисты присоединились к акции «Мы вместе»", "www.michurinsk.ru", "www.michurinsk.ru/news/society/33397.html"],
[22849595, "В Татарстане произошла ужасная авария, которая унесла жизни 2 человек", "nurlat-tat.ru", "nurlat-tat.ru/news/novosti/v-tatarstane-proizoshla-uzhasnaya-avariya-kotoraya-unesla-zhizni-2-chelovek"],
[66563162, "Житель области угрожал медикам по телефону после часового ожидания скорой", "kgd.ru", "kgd.ru/news/medicine/item/92703-zhitel-oblasti-ugrozhal-medikam-po-telefonu-posle-chasovogo-ozhidaniya-skoroj"],
[55803319, "Напал с фаллоимитатором? В Татарстане мужчину обвинили в разврате с 15-летней девочкой", "indienews.ru", "indienews.ru/napal-s-falloimittoom-na-devochku/"],
[15491744, "Связанная с X5 Retail компания решила частично отсудить бренд основателя группы &quot;Чиж&amp;Co&quot;", "tass.ru", "tass.ru/ekonomika/10200859"],
[12220210, "Зарубежный сервис назвал популярных российских исполнителей за рубежом", "tvzvezda.ru", "tvzvezda.ru/news/vstrane_i_mire/content/20201281521-s4M16.html"],
[58888161, "Осталась форма, пропало содержание: в Москве закрылся уникальный Дом фарфора. Вести в 20:00", "vesti.ru", "vesti.ru/video/2247947"],
[31362102, "В Вышнем Волочке загорелся дом с хлебным павильоном на Урицкого", "vedtver.ru", "vedtver.ru/news/proisshestviya/v-vyshnem-volochke-zagorelsya-dom-s-khlebnym-pavilonom-na-uritskogo/"],
[29957198, "Жителя Воронежской области 4 раза заподозрили в правонарушениях его тезок", "riavrn.ru", "riavrn.ru/districts/povorinsky/zhitelya-voronezhskoj-oblasti-4-raza-zapodozrili-v-pravonarusheniyah-ego-tezok/"],
[39089251, "Перечислены необходимые лекарства в доме при пандемии", "rostoday.com", "rostoday.com/perechisleny-neobhodimye-lekarstva-v-dome-pri-pandemii/"],
];