from .animal_advertisement import AnimalAdvertisementView
from .animal_news import AnimalNewsView
from .animal_advertisement_color import AnimalAdvertisementColorView
from .animal_advertisement_type import AnimalAdvertisementTypeView
from .favorit_animal import FavoritAnimal
from .animal_comment import CommentAnimal
