# Generated by Django 2.2.12 on 2020-07-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listanimal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewestLogFileContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_filename', models.CharField(max_length=200, verbose_name='название файла логера')),
                ('content', models.TextField(null=True, verbose_name='Последние 100 строк файла')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Последние записи логов по файлам',
                'verbose_name_plural': 'Последние записи логов по файлам',
            },
        ),
    ]
