# Generated by Django 2.2.12 on 2020-09-27 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listanimal', '0002_auto_20200927_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalnews',
            name='gallery_img',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), size=None),
        ),
    ]
