# Generated by Django 3.1 on 2020-12-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listanimal', '0002_auto_20201216_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalnews',
            name='comment',
        ),
        migrations.AddField(
            model_name='animalnews',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='listanimal.Comment'),
        ),
    ]
