# Generated by Django 2.2.12 on 2020-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listanimal', '0002_newestlogfilecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalnews',
            name='time_post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newestlogfilecontent',
            name='content',
            field=models.TextField(null=True, verbose_name='Запись файла'),
        ),
    ]
