# Generated by Django 3.1 on 2020-12-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listanimal', '0003_auto_20201216_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalinfo',
            name='comment',
        ),
        migrations.AddField(
            model_name='animalinfo',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='listanimal.Comment'),
        ),
    ]
