# Generated by Django 2.2.12 on 2020-08-13 09:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listanimal', '0003_auto_20200808_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalnews',
            name='gallery_img',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=None, size=None),
        ),
    ]
