# Generated by Django 3.1 on 2020-12-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listanimal', '0005_auto_20201216_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalinfo',
            name='comment',
            field=models.ManyToManyField(blank=True, to='listanimal.Comment'),
        ),
        migrations.AlterField(
            model_name='animalnews',
            name='comment',
            field=models.ManyToManyField(blank=True, to='listanimal.Comment'),
        ),
    ]
