# Generated by Django 3.1 on 2021-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listanimal', '0007_auto_20201225_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalinfo',
            name='size',
            field=models.CharField(choices=[('LARGE', 'Large'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], max_length=200),
        ),
    ]
